-- This module is the root of the EffectiveMordellCanonicalLaneLean Lean proof package.
import EffectiveMordellCanonicalLaneLean.Basic
import EffectiveMordellCanonicalLaneLean.SourcePackage
import EffectiveMordellCanonicalLaneLean.SourceDependencies
import EffectiveMordellCanonicalLaneLean.Formalization
import EffectiveMordellCanonicalLaneLean.ReviewerBridge
import EffectiveMordellCanonicalLaneLean.TheoremStatement
import EffectiveMordellCanonicalLaneLean.MathlibObjects
import EffectiveMordellCanonicalLaneLean.AdmissibleClass
import EffectiveMordellCanonicalLaneLean.Projection
import EffectiveMordellCanonicalLaneLean.BridgeLemmas
import EffectiveMordellCanonicalLaneLean.GateLemmas
import EffectiveMordellCanonicalLaneLean.FinalTheorem
import EffectiveMordellCanonicalLaneLean.MathlibStatement
